[package]
name = "lamian"
version = "0.1.0"
edition = "2021"
description = "LaMian CLI core"
license = "MIT"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
eframe = "0.27.2"
flate2 = "1.1.5"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
sha2 = "0.10.9"
tar = "0.4.44"
thiserror = "2.0.17"

[dev-dependencies]
tempfile = "3.23.0"
