"""Monthly Markdown reminder for Stage 2 results (topic-relevant papers).

Generates a tier-grouped Markdown file with paper titles, DOI links,
journal names, dates, and matched topics.
"""

from datetime import datetime
from pathlib import Path

from models import JournalArticle


def generate_reminder(
    scored_papers: list,
    reminder_dir: Path,
    month_str: str = "",
) -> Path:
    """Generate or append to a monthly reminder Markdown file.

    Args:
        scored_papers: List of ScoredPaper from project1's scorer.
        reminder_dir: Directory for reminder files.
        month_str: Month string for filename (e.g. "2026-02"). Defaults to current.

    Returns:
        Path to the reminder file.
    """
    if not month_str:
        month_str = datetime.now().strftime("%Y-%m")

    reminder_dir = Path(reminder_dir)
    reminder_dir.mkdir(parents=True, exist_ok=True)
    filepath = reminder_dir / f"{month_str}.md"

    # Load existing DOIs to avoid duplicates
    existing_dois = _load_existing_dois(filepath)

    # Group by tier
    from scorer import Tier, group_by_tier, filter_by_tier
    filtered = filter_by_tier(scored_papers, Tier.COULD_BE_INTERESTING)
    groups = group_by_tier(filtered)

    # Build new entries
    new_entries: dict[str, list[str]] = {}
    tier_labels = {
        Tier.MOST_RELEVANT: "Most Relevant",
        Tier.SOMEWHAT_RELEVANT: "Somewhat Relevant",
        Tier.COULD_BE_INTERESTING: "Could Be Interesting",
    }

    new_count = 0
    for tier in [Tier.MOST_RELEVANT, Tier.SOMEWHAT_RELEVANT, Tier.COULD_BE_INTERESTING]:
        papers = groups.get(tier, [])
        if not papers:
            continue

        label = tier_labels[tier]
        entries = []

        for sp in papers:
            paper = sp.paper
            # Dedup: use DOI if available, else title
            dedup_key = _get_dedup_key(paper)
            if dedup_key in existing_dois:
                continue
            existing_dois.add(dedup_key)

            entry = _format_entry(sp)
            entries.append(entry)
            new_count += 1

        if entries:
            new_entries[label] = entries

    if not new_entries:
        print(f"  Reminder: no new papers to add for {month_str}")
        return filepath

    # Write or append
    _write_reminder(filepath, new_entries, month_str)
    print(f"  Reminder: added {new_count} papers to {filepath}")
    return filepath


def _get_dedup_key(paper) -> str:
    """Get dedup key from a paper (ScoredPaper.paper or JournalArticle)."""
    if hasattr(paper, "doi") and paper.doi:
        return paper.doi
    return paper.title.strip().lower()


def _load_existing_dois(filepath: Path) -> set[str]:
    """Load DOIs and titles already in the reminder file for dedup."""
    dois = set()
    if not filepath.exists():
        return dois

    text = filepath.read_text(encoding="utf-8")
    # Extract DOI links: [doi](https://doi.org/10.xxx)
    import re
    for match in re.finditer(r"https://doi\.org/(10\.[^\s\)]+)", text):
        dois.add(match.group(1))

    return dois


def _format_entry(scored_paper) -> str:
    """Format a single scored paper as a Markdown list item."""
    paper = scored_paper.paper
    score = scored_paper.score
    tier = scored_paper.tier.value

    # Get title and DOI/URL
    title = paper.title if hasattr(paper, "title") else str(paper)
    doi = getattr(paper, "doi", "")
    url = getattr(paper, "url", "")
    journal = getattr(paper, "journal", "")
    published = getattr(paper, "published", "")

    # Build link
    if doi:
        link = f"[{title}](https://doi.org/{doi})"
    elif url:
        link = f"[{title}]({url})"
    else:
        link = title

    # Matched topics
    topics = scored_paper.matched_topics
    topics_str = ", ".join(topics[:3]) if topics else ""

    parts = [f"- {link}"]
    meta = []
    if journal:
        meta.append(journal.upper())
    if published:
        meta.append(published[:10])
    meta.append(f"score={score:.1f}")
    if topics_str:
        meta.append(topics_str)

    if meta:
        parts.append(f"  ({'; '.join(meta)})")

    return "".join(parts)


def _write_reminder(filepath: Path, new_entries: dict[str, list[str]], month_str: str) -> None:
    """Write or append tier-grouped entries to the reminder file."""
    if not filepath.exists():
        # Create new file with header
        lines = [
            f"# Journal Digest - {month_str}",
            "",
            f"Generated by project3 (Periodic Journal Summary).",
            "",
        ]
    else:
        lines = ["\n---\n", f"Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ""]

    for label, entries in new_entries.items():
        lines.append(f"## {label}")
        lines.append("")
        lines.extend(entries)
        lines.append("")

    with open(filepath, "a", encoding="utf-8") as f:
        f.write("\n".join(lines))
